# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6bbf4fef31eddf25d076f57c6b77297b414267819295870a99766a90095692f976b999d8a55ae59d7658ba29d6c7be6ae0d100ae82c96405aed5ccc4345c2bd

test:
  secret_key_base: b5e740ce7e81f6b804772298dfeb67138f7164e51714db94b7bd53d0b613f287c6a25284ce3f7e3a86852306d232b934a51bed18e0bdbcbff40174aadce262d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
